In [ ]:
########################################################################################################################
# Filename: RNN_Paragraph_Classification.ipynb
#
# Purpose: Multi-label Text-categorization, using recurrent neural networks, for paragraph-level
#          data as part of STAT 6500 final project.

# Author(s): Bobby (Robert) Lumpkin
#
# Library Dependencies: numpy, pandas, tensorflow, bpmll
########################################################################################################################

# Paragraph Classification Using RNNs

In [1]:
import numpy as np
import pandas as pd
import os
import random
import tensorflow as tf
import tensorflow_addons as tfa
from bpmll import bp_mll_loss
from sklearn.model_selection import train_test_split
from sklearn import metrics
import sys
sys.path.append('../ThresholdFunctionLearning')    ## Append path to the ThresholdFunctionLearning directory to the interpreters
                                                   ## search path
from threshold_learning import predict_test_labels_binary    ## Import the 'predict_test_labels_binary()' function from the 
                                                             ## threshold_learning library

In [2]:
## Load 'content_paragraphs_ready.csv' into a pandas dataframe
data_filepath = "..\..\dataset\content_paragraphs_ready.csv"
paragraph_data = pd.read_csv(data_filepath)
paragraph_data.head()

para_id                                          full_text  \
0   214236  MURPHY: Again Martha we are defacto staying at...   
1   214232  GOV. PHIL MURPHY, (D-NJ): Yes. Good to be back...   
2   214266  BEAUMONT (ON SCREEN UPPER LEFT - "FRIDAY MARCH...   
3   214246  But in the meantime, my message to Louisiana i...   
4   214238  MURPHY: Yeah listen, we had gotten another shi...   

   threats/impacts  responses/actions  severity  susceptibility  \
0                1                  1         0               1   
1                1                  1         1               1   
2                0                  1         0               0   
3                1                  1         1               0   
4                0                  1         0               0   

   self-efficacy  external-efficacy  response efficacy  public health  ...  \
0              1                  0                  1              1  ...   
1              1                  0                  1              1  ...   
2              0                  1                  0              1  ...   
3              1                  0                  1              1  ...   
4              0                  1                  0              1  ...   

   prosper  preview  moor  coverag  glow  profil  clash  incumb  frequent  \
0      0.0      0.0   0.0      0.0   0.0     0.0    0.0     0.0       0.0   
1      0.0      0.0   0.0      0.0   0.0     0.0    0.0     0.0       0.0   
2      0.0      0.0   0.0      0.0   0.0     0.0    0.0     0.0       0.0   
3      0.0      0.0   0.0      0.0   0.0     0.0    0.0     0.0       0.0   
4      0.0      0.0   0.0      0.0   0.0     0.0    0.0     0.0       0.0   

  unfound  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0  

[5 rows x 2119 columns]

In [3]:
## Keep only the paragraph id, paragraph text, and labels
to_keep = paragraph_data.columns[0:15]
#to_keep
paragraph_data = paragraph_data[to_keep]
paragraph_data.head()

para_id                                          full_text  \
0   214236  MURPHY: Again Martha we are defacto staying at...   
1   214232  GOV. PHIL MURPHY, (D-NJ): Yes. Good to be back...   
2   214266  BEAUMONT (ON SCREEN UPPER LEFT - "FRIDAY MARCH...   
3   214246  But in the meantime, my message to Louisiana i...   
4   214238  MURPHY: Yeah listen, we had gotten another shi...   

   threats/impacts  responses/actions  severity  susceptibility  \
0                1                  1         0               1   
1                1                  1         1               1   
2                0                  1         0               0   
3                1                  1         1               0   
4                0                  1         0               0   

   self-efficacy  external-efficacy  response efficacy  public health  \
0              1                  0                  1              1   
1              1                  0                  1              1   
2              0                  1                  0              1   
3              1                  0                  1              1   
4              0                  1                  0              1   

   economy  education  political evaluation  racial conflict  \
0        0          0                     0                0   
1        0          0                     0                0   
2        0          0                     0                0   
3        0          0                     0                0   
4        0          0                     0                0   

   international ralations/foreign policies  
0                                         0  
1                                         0  
2                                         0  
3                                         0  
4                                         0

In [4]:
# Preprocessing
import re
import string

def remove_URL(text):
    url = re.compile(r"https?://\S+|www\.\S+")
    return url.sub(r"", text)

# https://stackoverflow.com/questions/34293875/how-to-remove-punctuation-marks-from-a-string-in-python-3-x-using-translate/34294022
def remove_punct(text):
    translator = str.maketrans("", "", string.punctuation)
    return text.translate(translator)

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [5]:
pattern = re.compile(r"https?://(\S+|www)\.\S+")
for t in paragraph_data.full_text:
    matches = pattern.findall(t)
    for match in matches:
        print(t)
        print(match)
        print(pattern.sub(r"", t))
    if len(matches) > 0:
        break

In [6]:
paragraph_data["full_text"] = paragraph_data.full_text.map(remove_URL) # map(lambda x: remove_URL(x))
paragraph_data["full_text"] = paragraph_data.full_text.map(remove_punct)

In [7]:
# remove stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

# Stop Words: A stop word is a commonly used word (such as “the”, “a”, “an”, “in”) that a search engine
# has been programmed to ignore, both when indexing entries for searching and when retrieving them 
# as the result of a search query.
stop = set(stopwords.words("english"))

# https://stackoverflow.com/questions/5486337/how-to-remove-stop-words-using-nltk-or-python
def remove_stopwords(text):
    filtered_words = [word.lower() for word in text.split() if word.lower() not in stop]
    return " ".join(filtered_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rober\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
paragraph_data["full_text"] = paragraph_data.full_text.map(remove_stopwords)

In [9]:
from collections import Counter

# Count unique words
def counter_word(text_col):
    count = Counter()
    for text in text_col.values:
        for word in text.split():
            count[word] += 1
    return count

counter = counter_word(paragraph_data.full_text)

In [10]:
num_unique_words = len(counter)
counter.most_common(5)

[('said', 69), ('people', 61), ('trump', 49), ('new', 48), ('tests', 47)]

In [11]:
## Define the X and Y train and test matrices
covariate_cols = ['full_text']
label_cols = paragraph_data.columns.difference(['para_id'] + covariate_cols)

X = paragraph_data.full_text.to_numpy()
Y = paragraph_data[label_cols].to_numpy().astype(float)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.33, random_state = 321)

In [12]:
X_train.shape

(194,)

In [13]:
# Tokenize
from tensorflow.keras.preprocessing.text import Tokenizer

# vectorize a text corpus by turning each text into a sequence of integers
tokenizer = Tokenizer(num_words = num_unique_words)
tokenizer.fit_on_texts(X_train) # fit only to training
word_index = tokenizer.word_index

In [14]:
train_sequences = tokenizer.texts_to_sequences(X_train)
test_sequences = tokenizer.texts_to_sequences(X_test)

In [15]:
print(X_train[0])
print(train_sequences[0])

johnson asked 70 local savannah religious leaders keep worship centers closed none leaders said would reopen johnson told religious leaders understood financial burden religious institutions closed said reach god without going building”
[478, 72, 829, 830, 831, 316, 178, 114, 832, 228, 229, 833, 178, 1, 23, 230, 478, 57, 316, 178, 834, 144, 835, 316, 836, 229, 1, 479, 837, 179, 3, 838]


In [16]:
max_par_length = 0
for par in train_sequences:
    if len(par) > max_par_length:
        max_par_length = len(par)
        
max_par_length

86

In [17]:
# Pad the sequences to have the same length
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Max number of words in a sequence
max_length = 100

train_padded = pad_sequences(train_sequences, maxlen = max_length, padding = "post", truncating = "post")
test_padded = pad_sequences(test_sequences, maxlen = max_length, padding = "post", truncating = "post")
train_padded.shape, test_padded.shape

((194, 100), (96, 100))

In [18]:
# Check reversing the indices
# flip (key, value)
reverse_word_index = dict([(idx, word) for (word, idx) in word_index.items()])

def decode(sequence):
    return " ".join([reverse_word_index.get(idx, "?") for idx in sequence])

In [19]:
decoded_text = decode(train_sequences[0])

print(train_sequences[0])
print(decoded_text)

[478, 72, 829, 830, 831, 316, 178, 114, 832, 228, 229, 833, 178, 1, 23, 230, 478, 57, 316, 178, 834, 144, 835, 316, 836, 229, 1, 479, 837, 179, 3, 838]
johnson asked 70 local savannah religious leaders keep worship centers closed none leaders said would reopen johnson told religious leaders understood financial burden religious institutions closed said reach god without going building”


## Train a Simple RNN

In [67]:
## Define the simple RNN architecture
num_labels = len(label_cols)

model_simpleRNN = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(num_unique_words, 32, input_length = max_length),
    tf.keras.layers.SimpleRNN(16, return_sequences = False, return_state = False),
    #tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(num_labels, activation = 'sigmoid')
])

optim = tf.keras.optimizers.Adam(lr=0.0001)

#metrics = tfa.metrics.hamming_loss_fn(mode = 'multi-label')
model_simpleRNN.compile(loss = 'categorical_crossentropy', optimizer = optim)

In [63]:
tf.random.set_seed(123)
model_simpleRNN.fit(train_padded, Y_train, epochs = 100, validation_data = (test_padded, Y_test), verbose=2)

Epoch 1/100
7/7 - 2s - loss: 7.6402 - val_loss: 7.8881
Epoch 2/100
7/7 - 0s - loss: 7.6057 - val_loss: 7.8699
Epoch 3/100
7/7 - 0s - loss: 7.5747 - val_loss: 7.8509
Epoch 4/100
7/7 - 0s - loss: 7.5452 - val_loss: 7.8327
Epoch 5/100
7/7 - 0s - loss: 7.5174 - val_loss: 7.8150
Epoch 6/100
7/7 - 0s - loss: 7.4897 - val_loss: 7.7966
Epoch 7/100
7/7 - 0s - loss: 7.4609 - val_loss: 7.7773
Epoch 8/100
7/7 - 0s - loss: 7.4315 - val_loss: 7.7573
Epoch 9/100
7/7 - 0s - loss: 7.4005 - val_loss: 7.7378
Epoch 10/100
7/7 - 0s - loss: 7.3696 - val_loss: 7.7201
Epoch 11/100
7/7 - 0s - loss: 7.3370 - val_loss: 7.6999
Epoch 12/100
7/7 - 0s - loss: 7.3020 - val_loss: 7.6820
Epoch 13/100
7/7 - 0s - loss: 7.2682 - val_loss: 7.6658
Epoch 14/100
7/7 - 0s - loss: 7.2312 - val_loss: 7.6518
Epoch 15/100
7/7 - 0s - loss: 7.1934 - val_loss: 7.6442
Epoch 16/100
7/7 - 0s - loss: 7.1578 - val_loss: 7.6425
Epoch 17/100
7/7 - 0s - loss: 7.1240 - val_loss: 7.6437
Epoch 18/100
7/7 - 0s - loss: 7.0898 - val_loss: 7.6363
E

In [64]:
## Using a constant 0.5 threshold function, get the hamming loss for the trained network on the test set
predictions = model_simpleRNN.predict(test_padded)
predictions_binary = model_simpleRNN.predict(test_padded)
for i in range(Y_test.shape[0]):
    for j in range(Y_test.shape[1]):
        if predictions_binary[i, j] > 0.5:
            predictions_binary[i, j] = 1
        else:
            predictions_binary[i, j] = 0

# Get the hamming loss
metrics.hamming_loss(Y_test, predictions_binary)

0.4583333333333333

In [65]:
## Learn a Threshold Function
Y_train_pred = model_simpleRNN.predict(train_padded)
Y_test_pred = model_simpleRNN.predict(test_padded)
t_range = (0, 1)

test_labels_binary, threshold_function = predict_test_labels_binary(Y_train_pred, Y_train, Y_test_pred, t_range)
metrics.hamming_loss(Y_test, test_labels_binary)

0.23557692307692307

In [56]:
Y_test[0,]

array([0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.])

In [57]:
test_labels_binary[0,]

array([0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.])

## Train an LSTM model

In [147]:
## Define the LSTM RNN architecture
num_labels = len(label_cols)

model_LSTM = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(num_unique_words, 32, input_length = max_length),
    tf.keras.layers.LSTM(16, return_sequences = False, return_state = False),
    #tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(num_labels, activation = 'sigmoid')
])

optim = tf.keras.optimizers.Adam(lr=0.0001)
#optim_func_LSTM = tf.keras.optimizers.Adagrad(
#    learning_rate = 0.001, initial_accumulator_value = 0.1, epsilon = 1e-07,
#    name = 'Adagrad')

#metrics = tfa.metrics.hamming_loss_fn(mode = 'multi-label')
model_LSTM.compile(loss = 'categorical_crossentropy', optimizer = optim)

In [148]:
tf.random.set_seed(123)
model_LSTM.fit(train_padded, Y_train, epochs = 50, validation_data = (test_padded, Y_test), verbose=2)

Epoch 1/50
7/7 - 3s - loss: 7.7051 - val_loss: 7.9704
Epoch 2/50
7/7 - 0s - loss: 7.6989 - val_loss: 7.9639
Epoch 3/50
7/7 - 0s - loss: 7.6925 - val_loss: 7.9572
Epoch 4/50
7/7 - 0s - loss: 7.6863 - val_loss: 7.9505
Epoch 5/50
7/7 - 0s - loss: 7.6800 - val_loss: 7.9439
Epoch 6/50
7/7 - 0s - loss: 7.6740 - val_loss: 7.9373
Epoch 7/50
7/7 - 0s - loss: 7.6677 - val_loss: 7.9303
Epoch 8/50
7/7 - 0s - loss: 7.6611 - val_loss: 7.9231
Epoch 9/50
7/7 - 0s - loss: 7.6544 - val_loss: 7.9161
Epoch 10/50
7/7 - 0s - loss: 7.6479 - val_loss: 7.9089
Epoch 11/50
7/7 - 0s - loss: 7.6411 - val_loss: 7.9015
Epoch 12/50
7/7 - 0s - loss: 7.6341 - val_loss: 7.8939
Epoch 13/50
7/7 - 0s - loss: 7.6268 - val_loss: 7.8856
Epoch 14/50
7/7 - 0s - loss: 7.6192 - val_loss: 7.8770
Epoch 15/50
7/7 - 0s - loss: 7.6114 - val_loss: 7.8686
Epoch 16/50
7/7 - 0s - loss: 7.6035 - val_loss: 7.8596
Epoch 17/50
7/7 - 0s - loss: 7.5947 - val_loss: 7.8491
Epoch 18/50
7/7 - 0s - loss: 7.5855 - val_loss: 7.8379
Epoch 19/50
7/7 - 0

In [140]:
## Using a constant 0.5 threshold function, get the hamming loss for the trained network on the test set
predictions = model_LSTM.predict(test_padded)
predictions_binary = model_LSTM.predict(test_padded)
for i in range(Y_test.shape[0]):
    for j in range(Y_test.shape[1]):
        if predictions_binary[i, j] > 0.5:
            predictions_binary[i, j] = 1
        else:
            predictions_binary[i, j] = 0

# Get the hamming loss
metrics.hamming_loss(Y_test, predictions_binary)

0.5024038461538461

In [141]:
## Learn a Threshold Function
Y_train_pred = model_LSTM.predict(train_padded)
Y_test_pred = model_LSTM.predict(test_padded)
t_range = (0, 1)

test_labels_binary, threshold_function = predict_test_labels_binary(Y_train_pred, Y_train, Y_test_pred, t_range)
metrics.hamming_loss(Y_test, test_labels_binary)

0.17708333333333334

In [143]:
Y_test[0,]

array([0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.])

In [144]:
test_labels_binary[0,]

array([0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.])

## Train a Bidirectional LSTM

In [194]:
## Define the LSTM RNN architecture
num_labels = len(label_cols)

model_biLSTM = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(num_unique_words, 32, input_length = max_length),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(16, return_sequences = False, return_state = False)),
    #tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(num_labels, activation = 'sigmoid')
])

#optim = tf.keras.optimizers.Adam(lr=0.0001)
optim = tf.keras.optimizers.Adagrad(
    learning_rate = 0.001, initial_accumulator_value = 0.1, epsilon = 1e-07,
    name = 'Adagrad')

#optim = tf.keras.optimizers.RMSprop(learning_rate=0.001, rho=0.9, momentum = 0.8, epsilon=1e-07,)

#metrics = tfa.metrics.hamming_loss_fn(mode = 'multi-label')
model_biLSTM.compile(loss = 'categorical_crossentropy', optimizer = optim)

In [195]:
tf.random.set_seed(123)
model_biLSTM.fit(train_padded, Y_train, epochs = 100, validation_data = (test_padded, Y_test), verbose=2)

Epoch 1/100
7/7 - 9s - loss: 7.6779 - val_loss: 7.9388
Epoch 2/100
7/7 - 0s - loss: 7.6626 - val_loss: 7.9254
Epoch 3/100
7/7 - 0s - loss: 7.6504 - val_loss: 7.9143
Epoch 4/100
7/7 - 0s - loss: 7.6400 - val_loss: 7.9048
Epoch 5/100
7/7 - 0s - loss: 7.6311 - val_loss: 7.8965
Epoch 6/100
7/7 - 0s - loss: 7.6233 - val_loss: 7.8883
Epoch 7/100
7/7 - 0s - loss: 7.6155 - val_loss: 7.8802
Epoch 8/100
7/7 - 0s - loss: 7.6077 - val_loss: 7.8737
Epoch 9/100
7/7 - 0s - loss: 7.6014 - val_loss: 7.8673
Epoch 10/100
7/7 - 0s - loss: 7.5951 - val_loss: 7.8610
Epoch 11/100
7/7 - 0s - loss: 7.5889 - val_loss: 7.8552
Epoch 12/100
7/7 - 0s - loss: 7.5834 - val_loss: 7.8489
Epoch 13/100
7/7 - 0s - loss: 7.5771 - val_loss: 7.8428
Epoch 14/100
7/7 - 0s - loss: 7.5714 - val_loss: 7.8382
Epoch 15/100
7/7 - 0s - loss: 7.5669 - val_loss: 7.8332
Epoch 16/100
7/7 - 0s - loss: 7.5620 - val_loss: 7.8271
Epoch 17/100
7/7 - 0s - loss: 7.5561 - val_loss: 7.8220
Epoch 18/100
7/7 - 0s - loss: 7.5511 - val_loss: 7.8169
E

In [196]:
## Using a constant 0.5 threshold function, get the hamming loss for the trained network on the test set
predictions = model_biLSTM.predict(test_padded)
predictions_binary = model_biLSTM.predict(test_padded)
for i in range(Y_test.shape[0]):
    for j in range(Y_test.shape[1]):
        if predictions_binary[i, j] > 0.5:
            predictions_binary[i, j] = 1
        else:
            predictions_binary[i, j] = 0

# Get the hamming loss
metrics.hamming_loss(Y_test, predictions_binary)

0.5208333333333334

In [197]:
## Learn a Threshold Function
Y_train_pred = model_biLSTM.predict(train_padded)
Y_test_pred = model_biLSTM.predict(test_padded)
t_range = (0, 1)

test_labels_binary, threshold_function = predict_test_labels_binary(Y_train_pred, Y_train, Y_test_pred, t_range)
metrics.hamming_loss(Y_test, test_labels_binary)

0.20112179487179488

In [198]:
Y_test[0,]

array([0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.])

In [199]:
test_labels_binary[0,]

array([0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.])